### ISSUE TITLE
Assignment 8 Submission

### ISSUE THREAD

**Issue by chbackstrom** [chbackstrom/Assignment-8#1]
As per the Assignment 8 instructions, I have updated this repository with a .Rmd file of a presentation describing myself and my feedback on the data science course. All associated files are also stored in the Repo. Thanks again for the excellent course!

**Comment by mdscheuerell** [comment]
Well done, Callum. Your photo makes me think I could really use a vacation about now...

And I'm glad you enjoyed the course.
